image: node:latest

stages:
    - build
    - test

cache:
    paths:
        - backend/node_modules/
        - frontend/node_modules/

frontend-build:
    stage: build
    tags:
        - test-run
    script:
        - cd frontend
        - echo "Building frontend"
        - npm install

backend-build:
    stage: build
    tags:
        - test-run

    script:
        - cd backend
        - echo "Building backend"
        - npm install

frontend-test:
    stage: test
    tags:
        - test-run
    script:
        - echo "Frontend testing"
        - cd frontend
        - npm run test

backend-test:
    stage: test
    tags:
        - test-run
    script:
        - echo "Backend testing"
        - cd backend
        - npm run test
