image: haverzard/node-mysql-ci:latest

stages:
    - build
    - test

services:
    - mysql:latest

cache:
    paths:
        - backend/node_modules/
        - frontend/node_modules/

# before_script:
#    - apt --assume-yes update
#    - apt --assume-yes install mysql-client
#    - mysql --version

frontend-build:
    stage: build
    tags:
        - test-run
    script:
        - cd frontend
        - echo "Building frontend"

backend-build:
    stage: build
    tags:
        - test-run

    before_script:
        - echo "Building database"
        - mysql --user=root --host=localhost --password="" -e 'CREATE DATABASE IF NOT EXISTS crowdsource;'
        - \n
        # - Get-Content database/crowdsource.sql | mysql -u root crowdsource

    script:
        - cd backend
        - echo "Building backend"
        - npm install

frontend-test:
    stage: test
    tags:
        - test-run
    script:
        - echo "Frontend testing not implemented yet"
        - ls frontend/

backend-test:
    stage: test
    tags:
        - test-run
    script:
        - echo "Backend testing not implemented yet"
        - ls backend/node_modules/