image: node:latest

stages:
    - build
    - test

# services:
#     - mysql:latest

cache:
    paths:
        - backend/node_modules/
        - frontend/node_modules/

frontend-build:
    stage: build
    tags:
        - test-run
    script:
        - cd frontend
        - echo "Building frontend"

backend-build:
    stage: build
    tags:
        - test-run

    script:
        - cd backend
        - echo "Building backend"

frontend-test:
    stage: test
    tags:
        - test-run
    script:
        - echo "Frontend testing not implemented yet"
        - ls frontend/

backend-test:
    stage: test
    tags:
        - test-run
    script:
        - echo "Backend testing"
        - npm run test
