image: node

stages:
    - build
    - test

frontend-build:
    stage: build
    tags:
        - test-run
    script:
        - cd frontend
        - echo "Building frontend"

backend-build:
    stage: build
    tags:
        - test-run
    script:
        - cd backend
        - echo "Building backend"
        - npm install

frontend-test:
    stage: test
    tags:
        - test-run
    script:
        - echo "Frontend testing not implemented yet"

backend-test:
    stage: test
    tags:
        - test-run
    script:
        - echo "Backend testing not implemented yet"
